function LinkFormatter(value, row, index) {
  return "<a href='" + value + ">See Image</a>";
};


var data = [
  {
    nombres: "Teodora Maria",
    Apellidos: "Cedeño",
    typtype: "B",
    yearyear: 1908,
    countrycountry: "Venezuela",
    state: "Sucre",
    city: "Carúpano",
    link: "https://www.familysearch.org/ark:/61903/1:1:DF41-296Z",
  },
  {
    nombres: "Carmen Maria",
    apellidos: "Hernandez Gonzalez",
    type: "B",
    year: 1908,
    country: "Venezuela",
    state: "Sucre",
    city: "Carúpano",
    link: "https://www.familysearch.org/ark:/61903/1:1:DFHK-6TPZ",
  },
  {
    nombres: "Francisca Saturnina",
    apellidostype: "Moya Hernandez",
    type: "B",
    year: 1908,
    country: "Venezuela",
    state: "Nueva Esparta",
    city: "Caricao",
    link: "https://www.familysearch.org/ark:/61903/1:1:DFHK-6Y2M",
  },
  {
    nombres: "Sandalio",
    apellidos: "Jimenez",
    type: "M",
    year: 1913,
    country: "Venezuela",
    state: "Sucre",
    city: "La Asuncion",
    link: "https://www.familysearch.org/records/images/image-details?page=1&place=2104138&rmsId=M99B-QGN&imageIndex=5&singleView=true",
  },
  {
    nombres: "Genera",
    apellidos: "Acosta de Jimenez",
    type: "M",
    year: 1913,
    country: "Venezuela",
    state: "Sucre",
    city: "Río Caribe",
    link: "https://www.familysearch.org/records/images/image-details?page=1&place=5366&rmsId=M99T-85P&imageIndex=5&singleView=true",
  },
  {
    nombres: "Cruz Maria",
    apellidos: "Fermin Leon",
    type: "M",
    year: 1913,
    country: "Venezuela",
    state: "Sucre",
    city: "Río Caribe",
    link: "https://www.familysearch.org/records/images/image-details?page=1&place=5366&rmsId=M99T-85P&imageIndex=5&singleView=true",
  },
  {
    nombres: "Feliciana",
    apellidos: "Ramirez de Fermin",
    type: "M",
    year: 1913,
    country: "Venezuela",
    state: "Sucre",
    city: "Río Caribe",
    link: "https://www.familysearch.org/records/images/image-details?page=1&place=5366&rmsId=M99T-85P&imageIndex=5&singleView=true",
  },
  {
    nombres: "Ascencion",
    apellidos: "Salas",
    type: "D",
    year: 1939,
    country: "Venezuela",
    state: "Monagas",
    city: "Caicara",
    link: "https://www.familysearch.org/records/images/image-details?page=1&place=1136041&rmsId=TH-909-83452-15137-1&imageIndex=4&singleView=true",
  },
  {
    nombres: "Carmen",
    apellidos: "Sifontes Garcia",
    type: "D",
    year: 1939,
    country: "Venezuela",
    state: "Monagas",
    city: "Caicara",
    link: "https://www.familysearch.org/records/images/image-details?page=1&place=1136041&rmsId=TH-909-83452-15137-1&imageIndex=5&singleView=true",
  },
  {
    nombres: "Pacifico",
    apellidos: "Guevara",
    type: "D",
    year: 1939,
    country: "Venezuela",
    state: "Monagas",
    city: "Caicara",
    link: "https://www.familysearch.org/records/images/image-details?page=1&place=1136041&rmsId=TH-909-83452-15137-1&imageIndex=7&singleView=true",
  },
  {
    nombres: "Josefina Isabel",
    apellidostype: "Bermudez Campo",
    type: "B",
    year: 1953,
    country: "Mexico",
    state: "Tamaulipas",
    city: "La Asuncion",
    link: "https://www.familysearch.org/records/images/image-details?page=1&place=5368&rmsId=M99R-59M&imageIndex=6&singleView=true",
  },
  {
    nombres: "Juana",
    apellidos: "Valerio",
    type: "B",
    year: 1953,
    country: "Mexico",
    state: "Jalisco",
    city: "Mexquitic",
    link: "https://www.familysearch.org/records/images/image-details?page=1&place=5368&rmsId=M99R-59M&imageIndex=9&singleView=true",
  },
  {
    nombres: "Gloria del Valle",
    apellidostype: "Brito Luna",
    type: "B",
    year: 1953,
    country: "Mexico",
    state: "Nueva Esparta",
    city: "La Asuncion",
    link: "https://www.familysearch.org/records/images/image-details?page=1&place=5368&rmsId=M99R-59M&imageIndex=10&singleView=true",
  },
];
